load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "main_test",
    srcs = ["main_test.cpp"],
    deps = [
        "//src/lib/Bai1:Bai1",
        "@com_google_googletest//:gtest_main",
    ],
)
